# Generated by Django 6.0 on 2026-01-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_options_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_status",
            field=models.CharField(default="pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет"), ("stripe", "Stripe")], max_length=10
            ),
        ),
    ]
