version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: lms_postgres_prod
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:7-alpine
    container_name: lms_redis_prod
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  web:
    build: .
    container_name: lms_web_prod
    volumes:
      - static_volume:/app/staticfiles
      - media_data:/app/media
    environment:
      - DEBUG=0
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  nginx:
    build:
      context: ./nginx
    container_name: lms_nginx_prod
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles:ro
      - media_data:/app/media:ro
    depends_on:
      - web
    restart: always

  celery:
    build: .
    container_name: lms_celery_prod
    command: celery -A config worker --loglevel=info -P solo
    volumes:
      - static_volume:/app/staticfiles
      - media_data:/app/media
    environment:
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
    restart: always

  celery-beat:
    build: .
    container_name: lms_celery_beat_prod
    command: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - static_volume:/app/staticfiles
      - media_data:/app/media
    environment:
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - db
    restart: always

volumes:
  postgres_data:
  media_data:
  static_volume:
