# Generated by Django 6.0 on 2025-12-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["id"], "verbose_name": "Урок", "verbose_name_plural": "Уроки"},
        ),
    ]
